---
- name: Setup pyenv and Python environment
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check if pyenv is already installed
      stat:
        path: "{{ lookup('env','HOME') }}/.pyenv"
      register: pyenv_exists

    - name: Install pyenv
      shell: curl https://pyenv.run | bash
      when: not pyenv_exists.stat.exists

    - name: Add pyenv to PATH and initialize in ~/.zshrc
      lineinfile:
        path: "{{ lookup('env','HOME') }}/.zshrc"
        line: "{{ item }}"
        create: yes
      loop:
        - 'export PYENV_ROOT="$HOME/.pyenv"'
        - 'export PATH="$PYENV_ROOT/bin:$PATH"'
        - 'eval "$(pyenv init -)"'

    - name: Check if Python 3.12 is installed via pyenv
      shell: "{{ lookup('env','HOME') }}/.pyenv/bin/pyenv versions | grep -q '3.12.7'"
      register: python_312_check
      failed_when: false
      changed_when: false

    - name: Install Python 3.12.7 via pyenv
      shell: "{{ lookup('env','HOME') }}/.pyenv/bin/pyenv install 3.12.7"
      when: python_312_check.rc != 0

    - name: Set Python 3.12.7 as global default
      shell: "{{ lookup('env','HOME') }}/.pyenv/bin/pyenv global 3.12.7"
      when: python_312_check.rc != 0

    - name: Check if pyenv virtualenv pymadix exists
      shell: "{{ lookup('env','HOME') }}/.pyenv/bin/pyenv versions | grep -q '3.12.7/envs/pymadix'"
      register: pymadix_check
      failed_when: false
      changed_when: false

    - name: Create pyenv virtual environment pymadix
      shell: |
        export PYENV_ROOT="{{ lookup('env','HOME') }}/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv virtualenv 3.12.7 pymadix
      when: pymadix_check.rc != 0

    - name: Deactivate default virtual environment if active
      shell: |
        export PYENV_ROOT="{{ lookup('env','HOME') }}/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv deactivate 2>/dev/null || true
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Summary
      debug:
        msg:
          - "✓ Installed pyenv"
          - "✓ Installed Python 3.12.7 via pyenv"
          - "✓ Created pymadix virtual environment"
          - ""
          - "⚠️  IMPORTANT: Run the following command to activate the environment:"
          - "    pyenv activate pymadix"
          - ""
          - "✓ Ready to install packages with pip in pymadix environment"

